### ISSUE TITLE
Add instructions on how to use GPM/GVP

### ISSUE THREAD

**Issue by coruus** [yahoo/keyshop#1]

**Comment by dmitris** [comment]
I believe http://technosophos.com/2014/05/29/why-gpm-is-the-right-go-package-manager.html is a good write-up on how to use gpm and gvp (leaving aside a contentious debate whether it is the "right" solution).

The README instructs to use "go get github.com/yahoo/keyshop/ks/cmd/... " for installation which seems to work well (at least no tests are failing) - does the user need to mess with gpm and gvp in this case?  Is it a recommendation or requirement for developers and contributors? If a tight control over the versions of dependencies is needed, I would recommend to vendor them - for example, like Camlistore is doing (see https://github.com/camlistore/camlistore and https://github.com/camlistore/camlistore/tree/master/third_party).  This would preserve the "go-gettability" of the project for the users and allow them to install / develop keyshop in a common (or user-specified) GOPATH without having to create a GOPATH "sandbox" specifically for this project.

**Comment by dmitris** [comment]
I'm going to close this as no longer relevant.  `go get` seems to work well enough, and if we decide to vendor dependencies or pin their versions, we will most likely use glide. for that
